baseURL: 'https://blog.mrsheep.xyz'
title: MrSheep's Blog
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu: 
      main:
          - identifier: archives
            name: Archives
            url: /archives/
            weight: 10
          - identifier: categories
            name: Categories
            url: /categories/
            weight: 20
          - identifier: tags
            name: 🏷️
            url: /tags/
            weight: 30
          - identifier: Search
            name: 🔍️
            url: /search
            weight: 40
  zh:
    languageName: ":hk:"
    languageAltTitle: Chinese Traditional
    weight: 2
    menu: 
      main:
          - identifier: archives
            name: Archives
            url: /archives/
            weight: 10
          - identifier: categories
            name: Categories
            url: /categories/
            weight: 20
          - identifier: tags
            name: 🏷️
            url: /tags/
            weight: 30
          - identifier: Search
            name: 🔍️
            url: /search
            weight: 40

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "MrSheep's Blog"
  description: "MrSheep's Blog"
  author: MrSheep
  images: "https://blog.mrsheep.xyz/images/avatar.png"
  ShowReadingTime: true
  ShowShareButtons: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false
  languageAltTitle: "Chinese"

  assets:
    # disableHLJS: true # to disable highlightjs
    disableFingerprinting: true

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: MrSheep
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: You have no idea where I came from. We have no idea where we are going.

  socialIcons:
    - name: github
      url: 'https://github.com/Mr-Sheep'
    - name: gitlab
      url: 'https://gitlab.com/MrSheep928'

  fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary



